[build]
  functions = "functions"
  publish = "dist"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
